spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_again_web_db
    username: root
    password: root1234 # you don't want your password to be in plain text visible to everyone
# you should use environment variables to store your password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


  profiles:
    active: load_demo_data


server:
  error:
    include-stacktrace: never #    this removes the stack trace from the error message